spring:
  datasource:
    url: jdbc:postgresql://postgres.czmaw44qsnde.sa-east-1.rds.amazonaws.com:5432/postgres
    username: d_caiodamiao
    password: caralho123
    driver-class-name: org.postgresql.Driver
  application:
    name: ecommerce
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect